# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

# https://goreleaser.com/customization/builds/
builds:
  - binary: url-parser-{{ .Os }}-{{ .Arch }}
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

    # https://github.com/mikefarah/yq/blob/master/.goreleaser.yaml#L15C1-L40C22
    targets:
      - darwin_amd64
      - darwin_arm64
      - freebsd_386
      - freebsd_amd64
      - freebsd_arm
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - linux_mips
      - linux_mips64
      - linux_mips64le
      - linux_mipsle
      - linux_ppc64
      - linux_ppc64le
      - linux_riscv64
      - linux_s390x
      - netbsd_386
      - netbsd_amd64
      - netbsd_arm
      - openbsd_386
      - openbsd_amd64
      - windows_386
      - windows_amd64
    no_unique_dist_dir: true

archives:
  - format: binary

checksum:
  name_template: "checksums.txt"

changelog:
  sort: ""
  filters:
    exclude:
      - "^docs:"
      - "^test:"
