#!/bin/bash

set -eo pipefail

goreleaser build --clean --snapshot

cd dist

# files generated by goreleaser
rm artifacts.json config.yaml metadata.json

# https://rhash.sourceforge.io/manpage.php
rhash -r --sha256 . -o checksums.txt
