name: release url-parser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  buildAndRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.6"

      # https://github.com/goreleaser/goreleaser-action
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "v2.4.8"
          install-only: true

      - name: Compile
        run: |
          sudo apt-get install rhash -y
          chmod +x ./scripts/compile.sh
          ./scripts/compile.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.event.repository.name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dist/*
